name: Contribution count

on:
  pull_request_review:
    types:
      - submitted
  push:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: './_data/fellows.yml'
          from: 'yaml'
          to: 'json'
      - uses: actions/github-script@v3
        id: increment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fellowsInfo = ${{ steps.yaml2json.outputs.data }};
            const contributor = fellowsInfo.filter((fellow) => {
              return fellow.github.split('/').pop() === context.payload.sender.login;
            })[0];
            if(contributor){
              if(context.payload.commits) {
                 contributor['commits'] += context.payload.commits.length;
              } else if( context.payload.review ) {
                contributor['reviews'] += 1;
              } else {
                contributor['issues'] += 1;
              }
            }
            return fellowsInfo;
      - run: echo '${{steps.increment.outputs.result}}' > temp.json
      - run: tail temp.json
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'temp.json'
          from: 'json'
          to: 'yaml'
      - run: echo '${{steps.json2yaml.outputs.data}}' > _data/fellows.yml
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: ${{env.GITHUB_WORKSPACE}}
          add: _data/fellows.yml
          branch: main
